export const PROJECTS = [
  {
    className: 'cat-energy',
    imgSource: 'img/cat.jpg',
    projectSource: 'https://cat-energy-gilt.vercel.app/index.html',
    name: 'Cat Energy',
    description: 'Магазин функионального питания для котов',
    alt: 'Превью картинка проекта Cat Energy',
    aria: 'Перейти на сайт проекта Cat Energy',
    age: 4,
    tags: ['adaptive', 'layout', 'javascript'],
  },
  {
    className: 'moon-bicycles',
    imgSource: 'img/moon.jpg',
    projectSource: 'https://vysotskii-moon.vercel.app/',
    name: 'Moon',
    description: 'Магазин велосипедов',
    alt: 'Превью картинка проекта Moon',
    aria: 'Перейти на сайт проекта Moon',
    age: 8,
    tags: ['adaptive', 'javascript', 'layout'],
  },
  {
    className: 'way-travel',
    imgSource: 'img/way-travel.jpg',
    projectSource: 'https://vysotskii-way.vercel.app/',
    name: 'Way',
    description: 'Лендинг тура по Европе',
    alt: 'Превью картинка проекта Way',
    aria: 'Перейти на сайт проекта Way',
    age: 7,
    tags: ['adaptive', 'javascript', 'layout'],
  },
  {
    className: 'keksobooking',
    imgSource: 'img/keksobooking.jpg',
    projectSource: 'https://keksobooking-ten.vercel.app/',
    name: 'Кексобукинг',
    description: 'Сервис размещения объявлений об аренде недвижимости',
    alt: 'Превью картинка проекта Кексобукинг',
    aria: 'Перейти на сайт проекта Кексобукинг',
    age: 6,
    tags: ['javascript'],
  },
  {
    className: 'mishka',
    imgSource: 'img/mishka.jpg',
    projectSource: 'https://mishka-hazel.vercel.app/',
    name: 'Мишка',
    description: 'Магазин вязаных игрушек',
    alt: 'Превью картинка проекта Мишка',
    aria: 'Перейти на сайт проекта Мишка',
    age: 5,
    tags: ['adaptive', 'javascript', 'layout'],
  },
  {
    className: 'gllacy',
    imgSource: 'img/gllacy.jpg',
    projectSource: 'https://gllacy-seven.vercel.app/',
    name: 'Глейси',
    description: 'Магазин мороженного',
    alt: 'Превью картинка проекта Глейси',
    aria: 'Перейти на сайт проекта Глейси',
    age: 1,
    tags: ['layout'],
  },
  {
    className: 'device',
    imgSource: 'img/device.jpg',
    projectSource: 'https://device.vercel.app/',
    name: 'Девайс',
    description: 'Магазин электронных аксессуаров',
    alt: 'Превью картинка проекта Девайс',
    aria: 'Перейти на сайт проекта Девайс',
    age: 2,
    tags: ['layout'],
  },
  {
    className: 'uber',
    imgSource: 'img/uber.jpg',
    projectSource: 'https://orangebisquit.github.io/Uber',
    name: 'Uber',
    description: 'Лендинг Uber для поиска водителей',
    alt: 'Превью картинка проекта Uber',
    aria: 'Перейти на сайт проекта Uber',
    age: 3,
    tags: ['adaptive', 'layout'],
  },
  {
    className: 'big-trip',
    imgSource: 'img/big-trip.png',
    projectSource: 'https://big-trip-brown.vercel.app/',
    name: 'Big Trip',
    description: 'Планирование поездки по городам Европы',
    alt: 'Превью картинка проекта Big Trip',
    aria: 'Перейти на сайт проекта Big Trip',
    age: 9,
    tags: ['javascript'],
  },
  {
    className: 'smart-device',
    imgSource: 'img/smart-device.png',
    projectSource: 'https://vysotskii-smart-device.vercel.app/',
    name: 'Smart Device',
    description: 'Производство и монтаж печатных плат',
    alt: 'Превью картинка проекта Smart Device',
    aria: 'Перейти на сайт проекта Smart Device',
    age: 10,
    tags: ['adaptive', 'javascript', 'layout'],
  },
  {
    className: 'ch-jewellery.png',
    imgSource: 'img/ch-jewellery.png',
    projectSource: 'https://vysotskii-rocket-jewellery.vercel.app/main.html',
    name: 'CH Jewellery',
    description: 'Магазин ювелирных изделий',
    alt: 'Превью картинка проекта CH Jewellery',
    aria: 'Перейти на сайт проекта CH Jewellery',
    age: 11,
    tags: ['adaptive', 'javascript', 'layout'],
  },
];

